// Banka 60 dvojic pojem <-> definice pro hru AI Act Pexeso.
// Zdroj: obsahovy-podklad.md, sekce 5 (Glosář 60 dvojic pojem-definice).
const CARDS_DATA = [
  { id: 1, term: "Umělá inteligence (AI)", definition: "Počítačový systém napodobující lidské myšlení a rozhodování" },
  { id: 2, term: "Strojové učení", definition: "Způsob, jak se počítač „učí“ z dat místo pevných pravidel" },
  { id: 3, term: "Velký jazykový model (LLM)", definition: "AI model natrénovaný na obrovském množství textu, umí generovat odpovědi" },
  { id: 4, term: "Neuronová síť", definition: "Matematický model inspirovaný fungováním lidského mozku" },
  { id: 5, term: "Trénování modelu", definition: "Proces, kterým se AI učí na datech před nasazením" },
  { id: 6, term: "Halucinace AI", definition: "Sebejistě vymyšlená, ale nepravdivá odpověď AI" },
  { id: 7, term: "Prompt", definition: "Zadání/dotaz, kterým řídíme odpověď AI" },
  { id: 8, term: "Generativní AI", definition: "AI, která vytváří nový text, obraz nebo zvuk" },
  { id: 9, term: "Algoritmus", definition: "Přesný postup kroků, podle kterého počítač řeší úlohu" },
  { id: 10, term: "Trénovací data", definition: "Data, na kterých se AI model učí rozpoznávat vzory" },

  { id: 11, term: "AI Act", definition: "Nařízení EU stanovující pravidla pro vývoj a používání umělé inteligence" },
  { id: 12, term: "Risk-based přístup", definition: "Čím větší riziko pro lidi, tím přísnější pravidla" },
  { id: 13, term: "Nepřijatelné riziko", definition: "Praktiky AI, které jsou v EU úplně zakázané (např. sociální scoring)" },
  { id: 14, term: "Vysoké riziko", definition: "AI systémy s přísnou regulací (např. v náboru, zdravotnictví, bankovnictví)" },
  { id: 15, term: "Omezené riziko", definition: "AI systémy s povinností transparentnosti (např. musí přiznat, že jde o chatbota)" },
  { id: 16, term: "Minimální riziko", definition: "Běžné AI nástroje bez zvláštních povinností (např. filtr spamu)" },
  { id: 17, term: "Deployer (provozovatel)", definition: "Organizace, která AI systém používá v praxi" },
  { id: 18, term: "Provider (poskytovatel)", definition: "Organizace, která AI systém vyvíjí nebo uvádí na trh" },
  { id: 19, term: "GPAI", definition: "Obecný model AI (např. velký jazykový model) s vlastními povinnostmi" },
  { id: 20, term: "AI Office", definition: "Útvar Evropské komise dohlížející na provádění AI Actu" },
  { id: 21, term: "Článek 4", definition: "Ustanovení AI Actu ukládající povinnost AI gramotnosti zaměstnanců" },
  { id: 22, term: "AI gramotnost", definition: "Dostatečná úroveň znalostí a dovedností k bezpečnému používání AI" },
  { id: 23, term: "Sociální scoring", definition: "Plošné hodnocení důvěryhodnosti občanů státem, v EU zakázané" },
  { id: 24, term: "Biometrická kategorizace", definition: "Třídění lidí podle biometrických znaků, silně omezené" },
  { id: 25, term: "Transparentnost AI", definition: "Povinnost přiznat, že s uživatelem komunikuje AI, ne člověk" },

  { id: 26, term: "Bias (zkreslení)", definition: "Nespravedlivé zvýhodnění/znevýhodnění kvůli chybným datům" },
  { id: 27, term: "Deepfake", definition: "Uměle vytvořené realistické video nebo hlas napodobující reálnou osobu" },
  { id: 28, term: "Ochrana osobních údajů", definition: "Povinnost chránit osobní data zpracovávaná i pomocí AI" },
  { id: 29, term: "GDPR", definition: "Evropské nařízení o ochraně osobních údajů, platí souběžně s AI Actem" },
  { id: 30, term: "Kybernetická bezpečnost AI", definition: "Ochrana AI systému proti zneužití či útoku" },
  { id: 31, term: "Black box", definition: "AI systém, jehož rozhodování zvenčí nelze snadno vysvětlit" },
  { id: 32, term: "Dezinformace", definition: "Nepravdivá informace, kterou AI dokáže snadno a rychle šířit" },
  { id: 33, term: "Manipulativní AI", definition: "Technika využívající AI k nekalému ovlivnění chování lidí (zakázáno)" },
  { id: 34, term: "Diskriminace algoritmem", definition: "Nerovné zacházení způsobené vzorci v datech, ne úmyslem" },
  { id: 35, term: "Odpovědnost za chybu AI", definition: "Odpovědnost nese organizace, která AI nasadila, ne AI samotná" },

  { id: 36, term: "Microsoft 365 Copilot", definition: "AI asistent integrovaný do Wordu, Excelu, Outlooku a Teams" },
  { id: 37, term: "Chatbot", definition: "Program simulující konverzaci s člověkem" },
  { id: 38, term: "Prompt engineering", definition: "Dovednost formulovat dotaz tak, aby AI dala nejlepší odpověď" },
  { id: 39, term: "Citlivá data", definition: "Údaje vyžadující zvýšenou ochranu (zdravotní, biometrické atd.)" },
  { id: 40, term: "Utajovaná informace", definition: "Informace, kterou nesmíme vkládat do veřejných AI nástrojů" },
  { id: 41, term: "Doplněk (plug-in)", definition: "Rozšíření, které AI nástroji přidává další funkce" },
  { id: 42, term: "Automatizace úkolů", definition: "Nechání AI vykonat rutinní činnost místo člověka" },
  { id: 43, term: "Shrnutí textu AI", definition: "Funkce, kdy AI zkrátí dlouhý dokument na hlavní body" },
  { id: 44, term: "Fact-checking", definition: "Ověření pravdivosti tvrzení, nutné i u odpovědí AI" },
  { id: 45, term: "Halucinovaná citace", definition: "Smyšlený odkaz na zdroj nebo zákon, který AI vydává za reálný" },

  { id: 46, term: "Strojový překlad", definition: "Automatický překlad textu pomocí AI" },
  { id: 47, term: "Rozpoznávání obličeje", definition: "Biometrická technologie identifikace osob z obrazu" },
  { id: 48, term: "Doporučovací systém", definition: "AI navrhující obsah/produkty na základě chování uživatele" },
  { id: 49, term: "Prediktivní policing", definition: "Predikce trestné činnosti pomocí AI, v EU silně omezeno" },
  { id: 50, term: "Scoring žádostí", definition: "Automatizované bodové hodnocení žádosti (např. o úvěr, o plnění)" },
  { id: 51, term: "Digitální stopa", definition: "Souhrn dat, která o sobě zanecháváme při používání online služeb" },
  { id: 52, term: "Etika AI", definition: "Zásady odpovědného a férového navrhování a používání AI" },
  { id: 53, term: "Vysvětlitelnost AI (explainability)", definition: "Schopnost srozumitelně popsat, proč AI rozhodla tak, jak rozhodla" },
  { id: 54, term: "Dohledový orgán", definition: "Národní úřad kontrolující dodržování AI Actu (od 8/2026)" },
  { id: 55, term: "Sankce za porušení AI Actu", definition: "Pokuty, které mohou dosáhnout desítek milionů eur" },
  { id: 56, term: "Certifikace shody (CE)", definition: "Označení, že vysoce rizikový AI systém splňuje požadavky" },
  { id: 57, term: "Technická dokumentace AI systému", definition: "Povinný popis fungování a rizik AI systému" },
  { id: 58, term: "Notifikovaná osoba", definition: "Subjekt oprávněný posuzovat shodu vysoce rizikových AI systémů" },
  { id: 59, term: "Oznámení incidentu", definition: "Povinnost nahlásit vážný incident způsobený AI systémem" },
  { id: 60, term: "Token", definition: "základní jednotka textu používaná modelem ke zpracování a generování jazyka" }
];
